services:
  web-proxy:
    image: nginx:alpine

  wis2box-ui:
    image: ghcr.io/wmo-im/wis2box-ui:1.0b8

  wis2box-webapp:
    image: ghcr.io/wmo-im/wis2box-webapp:0.2.1

  wis2box-api:
    image: ghcr.io/wmo-im/wis2box-api:1.0b8

  minio:
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z-cpuv1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2

  mosquitto:
    image: ghcr.io/wmo-im/wis2box-broker:1.0b8

  wis2box-management:
    image: ghcr.io/wmo-im/wis2box-management:1.0b8

  mqtt_metrics_collector:
    image: ghcr.io/wmo-im/wis2box-mqtt-metrics-collector:1.0b8

  wis2box-auth:
    image: ghcr.io/wmo-im/wis2box-auth:1.0b8

  wis2downloader:
    image: ghcr.io/wmo-im/wis2downloader:v0.3.1

  loki:
    image: grafana/loki:2.4.1

  prometheus:
    image: prom/prometheus:v2.37.0

  grafana:
    image: grafana/grafana:9.0.3

  elasticsearch-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest