# the following github action should publish the file wis2box.images as a release asset

name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  issues: write
  pull-requests: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./wis2box-images.json
          asset_name: wis2box-images.json
          asset_content_type: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}
  
