name: Publish Release Asset

on:
  release:
    types: [published]

permissions:
  contents: write
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: write
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Verify Asset File
        run: |
          if [ ! -f ./wis2box-images.json ]; then
            echo "Error: File 'wis2box-images.json' does not exist."
            exit 1
          fi
      - name: Debug Upload URL
        run: echo "${{ github.event.release.upload_url }}"
      - name: Test API Access
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/releases
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./docker-compose.images.yml
          asset_name: docker-compose.images.yml
          asset_content_type: application/json
  
